{"uuid": "b3903d37-3380-4746-8a2e-4324d0e95957", "counter": 46, "stdout": "fatal: [server1]: FAILED! => {\"msg\": \"The conditional check 'vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')' failed. The error was: error while evaluating conditional (vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')): 'default' is undefined\\n\\nThe error appears to be in '/home/bakvivas/Documents/Projects/ansible-role-3x-ui/roles/3x_ui_container/tasks/start_container.yml': line 14, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n- name: Debug vpn_username\\n  ^ here\\n\"}", "start_line": 50, "end_line": 51, "runner_ident": "9d100537-c864-4f58-9e60-06d0d4fd79cb", "event": "runner_on_failed", "pid": 9401, "created": "2024-12-03T22:33:45.431852+00:00", "parent_uuid": "985f4199-2370-f80e-6e60-00000000005b", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "5d48239f-07ef-4bce-9cd0-66cf1d626696", "play": "start docker", "play_uuid": "985f4199-2370-f80e-6e60-000000000002", "play_pattern": "3x_ui_server", "task": "Debug vpn_username", "task_uuid": "985f4199-2370-f80e-6e60-00000000005b", "task_action": "fail", "resolved_action": "ansible.builtin.fail", "task_args": "", "task_path": "/home/bakvivas/Documents/Projects/ansible-role-3x-ui/roles/3x_ui_container/tasks/start_container.yml:14", "role": "3x_ui_container", "host": "server1", "remote_addr": "server1", "res": {"msg": "The conditional check 'vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')' failed. The error was: error while evaluating conditional (vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')): 'default' is undefined\n\nThe error appears to be in '/home/bakvivas/Documents/Projects/ansible-role-3x-ui/roles/3x_ui_container/tasks/start_container.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Debug vpn_username\n  ^ here\n", "_ansible_no_log": false}, "start": "2024-12-03T22:33:45.421505+00:00", "end": "2024-12-03T22:33:45.431693+00:00", "duration": 0.010188, "ignore_errors": null, "event_loop": null, "uuid": "b3903d37-3380-4746-8a2e-4324d0e95957"}}